project:
  type: website
  output-dir: docs

website:
  title: "Yu-Yun Chang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false